"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Modal, Button } from "@/components/ui";
import { BackgroundPicker } from "@/components/background-picker";
import { publishedBackdrop } from "@/lib/blanks";
import { publishImage } from "@/app/designs/actions";

/**
 * Publish flow modal (#16). Replaces auto-publish: the owner sets name and
 * storefront backdrop before the design goes live, then lands on its public
 * page. A name left blank is auto-generated by Claude (publishImage fills the
 * gap), so it's optional friction. Descriptions are no longer collected or
 * auto-generated (2026-07-29 review).
 *
 * Backdrop picking (#140): the publish modal shows the FULL color palette
 * (not the /d page's collapsed 5-swatch row — see BackgroundPicker's
 * "full"/"collapsed" modes) and forces an explicit pick — no default,
 * Publish stays disabled until one is chosen. A live preview shows the
 * actual artwork on the candidate backdrop as the owner picks.
 */
export function PublishModal({
  imageId,
  imageUrl,
  open,
  onClose,
  from,
}: {
  /** Image to publish; null while the modal is closed. */
  imageId: string | null;
  /** Artwork to render in the live backdrop preview; null if unavailable
   * (the preview is skipped, picking still works). */
  imageUrl?: string | null;
  open: boolean;
  onClose: () => void;
  /** Origin recorded on the destination link so its "up"/Escape returns here. */
  from?: string;
}) {
  const router = useRouter();
  const [title, setTitle] = useState("");
  // No default (#140): publishing without an explicit backdrop pick is
  // blocked, so null is a real, initial state — not a placeholder.
  const [bg, setBg] = useState<string | null>(null);
  const [publishing, setPublishing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function confirm() {
    if (!imageId || !bg) return;
    setPublishing(true);
    setError(null);
    try {
      await publishImage(imageId, {
        title: title.trim() || undefined,
        backgroundColor: bg,
      });
      const suffix = from ? `?from=${encodeURIComponent(from)}` : "";
      router.push(`/d/${imageId}${suffix}`);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      setPublishing(false);
    }
  }

  const preview = bg
    ? publishedBackdrop(bg)
    : { className: "bg-checkerboard", style: undefined };

  return (
    <Modal
      open={open}
      onClose={publishing ? () => {} : onClose}
      className="w-[calc(100vw-2rem)] max-w-lg bg-background border border-border rounded-lg p-5 max-h-[90vh] overflow-y-auto"
    >
      <h2 className="text-lg font-bold">Publish to the Shop</h2>
      <p className="text-sm text-text-muted mt-1">
        Set how your design appears in the storefront.
      </p>

      <div className="space-y-4 mt-4">
        {imageUrl && (
          <div
            className={`rounded-lg overflow-hidden border border-border aspect-square flex items-center justify-center ${preview.className}`}
            style={preview.style}
            data-testid="publish-preview"
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={imageUrl}
              alt=""
              className="w-full h-full object-contain"
            />
          </div>
        )}
        <div>
          <label className="block text-sm font-medium mb-2">Name</label>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Auto-generated if blank"
            maxLength={80}
            className="w-full bg-surface border border-border rounded px-3 py-2"
          />
        </div>
        <BackgroundPicker
          value={bg}
          onChange={setBg}
          disabled={publishing}
          mode="full"
        />
      </div>

      {error && <p className="text-sm text-negative mt-3">{error}</p>}

      <div className="flex gap-2 mt-5">
        <Button
          onClick={confirm}
          disabled={publishing || !bg}
          className="flex-1"
        >
          {publishing ? "Publishing…" : "Publish"}
        </Button>
        <Button
          onClick={onClose}
          variant="ghost"
          disabled={publishing}
        >
          Cancel
        </Button>
      </div>
    </Modal>
  );
}
